#### Data Loading

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data_2023 = pd.read_csv("../data/spotify-2023.csv", encoding="utf-8", encoding_errors="ignore")
data_2024 = pd.read_csv("../data/spotify-2024.csv", encoding="utf-8", encoding_errors="ignore")

#### Dataset Analysis

In [3]:
# number of rows 

print("Number of rows in 2023 Dataset: ", len(data_2023))
print("Number of rows in 2024 Dataset: ", len(data_2024))

Number of rows in 2023 Dataset:  953
Number of rows in 2024 Dataset:  4600

In [4]:
# number of columns

print("Number of columns in 2023 Dataset: ", len(data_2023.columns.to_list()))
print("Number of columns in 2024 Dataset: ", len(data_2024.columns.to_list()))

Number of columns in 2023 Dataset:  24
Number of columns in 2024 Dataset:  29

In [5]:
# 2023 dataset datatype

data_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            953 non-null    object
 1   artist(s)_name        953 non-null    object
 2   artist_count          953 non-null    int64
 3   released_year         953 non-null    int64
 4   released_month        953 non-null    int64
 5   released_day          953 non-null    int64
 6   in_spotify_playlists  953 non-null    int64
 7   in_spotify_charts     953 non-null    int64
 8   streams               953 non-null    object
 9   in_apple_playlists    953 non-null    int64
 10  in_apple_charts       953 non-null    int64
 11  in_deezer_playlists   953 non-null    object
 12  in_deezer_charts      953 non-null    int64
 13  in_shazam_charts      903 non-null    object
 14  bpm                   953 non-null    int64
 15  key                   858 non-null    object
 16  mode                  953 non-null    object
 17  danceability_%        953 non-null    int64
 18  valence_%             953 non-null    int64
 19  energy_%              953 non-null    int64
 20  acousticness_%        953 non-null    int64
 21  instrumentalness_%    953 non-null    int64
 22  liveness_%            953 non-null    int64
 23  speechiness_%         953 non-null    int64
dtypes: int64(17), object(7)
memory usage: 178.8+ KB

In [6]:
# 2024 dataset datatype

data_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Track                       4600 non-null   object
 1   Album Name                  4600 non-null   object
 2   Artist                      4595 non-null   object
 3   Release Date                4600 non-null   object
 4   ISRC                        4600 non-null   object
 5   All Time Rank               4600 non-null   object
 6   Track Score                 4600 non-null   float64
 7   Spotify Streams             4487 non-null   object
 8   Spotify Playlist Count      4530 non-null   object
 9   Spotify Playlist Reach      4528 non-null   object
 10  Spotify Popularity          3796 non-null   float64
 11  YouTube Views               4292 non-null   object
 12  YouTube Likes               4285 non-null   object
 13  TikTok Posts                3427 non-null   object
 14  TikTok Likes                3620 non-null   object
 15  TikTok Views                3619 non-null   object
 16  YouTube Playlist Reach      3591 non-null   object
 17  Apple Music Playlist Count  4039 non-null   float64
 18  AirPlay Spins               4102 non-null   object
 19  SiriusXM Spins              2477 non-null   object
 20  Deezer Playlist Count       3679 non-null   float64
 21  Deezer Playlist Reach       3672 non-null   object
 22  Amazon Playlist Count       3545 non-null   float64
 23  Pandora Streams             3494 non-null   object
 24  Pandora Track Stations      3332 non-null   object
 25  Soundcloud Streams          1267 non-null   object
 26  Shazam Counts               4023 non-null   object
 27  TIDAL Popularity            0 non-null      float64
 28  Explicit Track              4600 non-null   int64
dtypes: float64(6), int64(1), object(22)
memory usage: 1.0+ MB

## Data Preparation and Cleaning

### Naming Convention and Data Type

In [7]:
# Change name for 2023 dataset

data_2023.columns = [col.replace("_", " ").title() for col in data_2023.columns]
data_2023.rename(columns={"Track Name": "Track", "Artist(S) Name": "Artist", "In Spotify Playlists": "Spotify Playlist Count 2023",
                             "Streams": "Streams 2023", "In Spotify Charts" : "Spotify Chart Counts 2023", "In Apple Playlists":"Apple Music Playlist Count 2023",
                             "In Apple Charts":"Apple Music Chart Counts 2023", "In Deezer Playlists":"Deezer Playlist Count 2023", "In Deezer Charts":"Deezer Chart Counts 2023",
                             "In Shazam Charts":"Shazam Chart Counts 2023"}, inplace=True)
data_2023.drop(columns=["Artist Count"], inplace=True)

In [8]:
# Convert datatype for 2023 dataset

for col in ["Streams 2023", "Deezer Playlist Count 2023", "Shazam Chart Counts 2023"]:
    data_2023[col] = data_2023[col].replace(",", "", regex=True)
    data_2023[col] = pd.to_numeric(data_2023[col], errors='coerce')

In [9]:
# Change name for 2024 dataset

data_2024.columns = data_2024.columns + " 2024"
data_2024.rename(columns={"Track 2024": "Track", "Album Name 2024": "Album Name", "Artist 2024":"Artist",
                             "Release Date 2024": "Release Date", "ISRC 2024":"ISRC", "All Time Rank 2024": "All Time Rank"}, inplace=True)
data_2024.drop(columns={"ISRC", "TIDAL Popularity 2024", "Explicit Track 2024"}, inplace=True)

In [10]:
# Convert datatype for 2024 dataset

numeric_cols = [col for col in data_2024.columns.to_list() if col not in ["Track", "Artist", "Release Date", "Album Name"]]
for col in numeric_cols:
    data_2024[col] = data_2024[col].replace(",", "", regex=True)
    data_2024[col] = pd.to_numeric(data_2024[col], errors='coerce')

In [11]:
data_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 23 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Track                            953 non-null    object
 1   Artist                           953 non-null    object
 2   Released Year                    953 non-null    int64
 3   Released Month                   953 non-null    int64
 4   Released Day                     953 non-null    int64
 5   Spotify Playlist Count 2023      953 non-null    int64
 6   Spotify Chart Counts 2023        953 non-null    int64
 7   Streams 2023                     952 non-null    float64
 8   Apple Music Playlist Count 2023  953 non-null    int64
 9   Apple Music Chart Counts 2023    953 non-null    int64
 10  Deezer Playlist Count 2023       953 non-null    int64
 11  Deezer Chart Counts 2023         953 non-null    int64
 12  Shazam Chart Counts 2023         903 non-null    float64
 13  Bpm                              953 non-null    int64
 14  Key                              858 non-null    object
 15  Mode                             953 non-null    object
 16  Danceability %                   953 non-null    int64
 17  Valence %                        953 non-null    int64
 18  Energy %                         953 non-null    int64
 19  Acousticness %                   953 non-null    int64
 20  Instrumentalness %               953 non-null    int64
 21  Liveness %                       953 non-null    int64
 22  Speechiness %                    953 non-null    int64
dtypes: float64(2), int64(17), object(4)
memory usage: 171.4+ KB

In [12]:
data_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Track                            4600 non-null   object
 1   Album Name                       4600 non-null   object
 2   Artist                           4595 non-null   object
 3   Release Date                     4600 non-null   object
 4   All Time Rank                    4600 non-null   int64
 5   Track Score 2024                 4600 non-null   float64
 6   Spotify Streams 2024             4487 non-null   float64
 7   Spotify Playlist Count 2024      4530 non-null   float64
 8   Spotify Playlist Reach 2024      4528 non-null   float64
 9   Spotify Popularity 2024          3796 non-null   float64
 10  YouTube Views 2024               4292 non-null   float64
 11  YouTube Likes 2024               4285 non-null   float64
 12  TikTok Posts 2024                3427 non-null   float64
 13  TikTok Likes 2024                3620 non-null   float64
 14  TikTok Views 2024                3619 non-null   float64
 15  YouTube Playlist Reach 2024      3591 non-null   float64
 16  Apple Music Playlist Count 2024  4039 non-null   float64
 17  AirPlay Spins 2024               4102 non-null   float64
 18  SiriusXM Spins 2024              2477 non-null   float64
 19  Deezer Playlist Count 2024       3679 non-null   float64
 20  Deezer Playlist Reach 2024       3672 non-null   float64
 21  Amazon Playlist Count 2024       3545 non-null   float64
 22  Pandora Streams 2024             3494 non-null   float64
 23  Pandora Track Stations 2024      3332 non-null   float64
 24  Soundcloud Streams 2024          1267 non-null   float64
 25  Shazam Counts 2024               4023 non-null   float64
dtypes: float64(21), int64(1), object(4)
memory usage: 934.5+ KB

In [13]:
# Make the realease day column

data_2023["Release Date"] = data_2023["Released Month"].astype(str) + "/" + data_2023["Released Day"].astype(str) + "/" + data_2023["Released Year"].astype(str)
data_2023.drop(columns=["Released Year", "Released Month", "Released Day"], inplace=True)

In [14]:
data_2023.columns

Index(['Track', 'Artist', 'Spotify Playlist Count 2023',
       'Spotify Chart Counts 2023', 'Streams 2023',
       'Apple Music Playlist Count 2023', 'Apple Music Chart Counts 2023',
       'Deezer Playlist Count 2023', 'Deezer Chart Counts 2023',
       'Shazam Chart Counts 2023', 'Bpm', 'Key', 'Mode', 'Danceability %',
       'Valence %', 'Energy %', 'Acousticness %', 'Instrumentalness %',
       'Liveness %', 'Speechiness %', 'Release Date'],
      dtype='object')

In [15]:
data_2024.columns

Index(['Track', 'Album Name', 'Artist', 'Release Date', 'All Time Rank',
       'Track Score 2024', 'Spotify Streams 2024',
       'Spotify Playlist Count 2024', 'Spotify Playlist Reach 2024',
       'Spotify Popularity 2024', 'YouTube Views 2024', 'YouTube Likes 2024',
       'TikTok Posts 2024', 'TikTok Likes 2024', 'TikTok Views 2024',
       'YouTube Playlist Reach 2024', 'Apple Music Playlist Count 2024',
       'AirPlay Spins 2024', 'SiriusXM Spins 2024',
       'Deezer Playlist Count 2024', 'Deezer Playlist Reach 2024',
       'Amazon Playlist Count 2024', 'Pandora Streams 2024',
       'Pandora Track Stations 2024', 'Soundcloud Streams 2024',
       'Shazam Counts 2024'],
      dtype='object')

In [16]:
# Reorder columns

cols_2023 = data_2023.columns.to_list()
cols_2023.remove("Release Date")
cols_2023.remove("Artist")

cols_2023.insert(1, "Artist")
cols_2023.insert(2, "Release Date")
data_2023 = data_2023[cols_2023]
data_2023

,Track,Artist,Release Date,Spotify Playlist Count 2023,Spotify Chart Counts 2023,Streams 2023,Apple Music Playlist Count 2023,Apple Music Chart Counts 2023,Deezer Playlist Count 2023,Deezer Chart Counts 2023,...,Bpm,Key,Mode,Danceability %,Valence %,Energy %,Acousticness %,Instrumentalness %,Liveness %,Speechiness %
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",7/14/2023,553,147,141381703.0,43,263,45,10,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,3/23/2023,1474,48,133716286.0,48,126,58,14,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,6/30/2023,1397,113,140003974.0,94,207,91,14,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,8/23/2019,7858,100,800840817.0,116,207,125,12,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,5/18/2023,3133,50,303236322.0,84,133,87,15,...,144,A,Minor,65,23,80,14,63,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,My Mind & Me,Selena Gomez,11/3/2022,953,0,91473363.0,61,13,37,1,...,144,A,Major,60,24,39,57,0,8,3
949,Bigger Than The Whole Sky,Taylor Swift,10/21/2022,1180,0,121871870.0,4,0,8,0,...,166,F#,Major,42,7,24,83,1,12,6
950,A Veces (feat. Feid),"Feid, Paulo Londra",11/3/2022,573,0,73513683.0,2,0,7,0,...,92,C#,Major,80,81,67,4,0,8,6
951,En La De Ella,"Feid, Sech, Jhayco",10/20/2022,1320,0,133895612.0,29,26,17,0,...,97,C#,Major,82,67,77,8,0,12,5
952,Alone,Burna Boy,11/4/2022,782,2,96007391.0,27,18,32,1,...,90,E,Minor,61,32,67,15,0,11,5

In [17]:
# Reorder columns

cols_2024 = data_2024.columns.to_list()
cols_2024.remove("Release Date")
cols_2024.remove("Artist")

cols_2024.insert(1, "Artist")
cols_2024.insert(2, "Release Date")
spotify_2024 = data_2024[cols_2024]
spotify_2024

,Track,Artist,Release Date,Album Name,All Time Rank,Track Score 2024,Spotify Streams 2024,Spotify Playlist Count 2024,Spotify Playlist Reach 2024,Spotify Popularity 2024,...,Apple Music Playlist Count 2024,AirPlay Spins 2024,SiriusXM Spins 2024,Deezer Playlist Count 2024,Deezer Playlist Reach 2024,Amazon Playlist Count 2024,Pandora Streams 2024,Pandora Track Stations 2024,Soundcloud Streams 2024,Shazam Counts 2024
0,MILLION DOLLAR BABY,Tommy Richman,4/26/2024,Million Dollar Baby - Single,1,725.4,3.904709e+08,30716.0,196631588.0,92.0,...,210.0,40975.0,684.0,62.0,17598718.0,114.0,18004655.0,22931.0,4818457.0,2669262.0
1,Not Like Us,Kendrick Lamar,5/4/2024,Not Like Us,2,545.9,3.237039e+08,28113.0,174597137.0,92.0,...,188.0,40778.0,3.0,67.0,10422430.0,111.0,7780028.0,28444.0,6623075.0,1118279.0
2,i like the way you kiss me,Artemas,3/19/2024,I like the way you kiss me,3,538.4,6.013093e+08,54331.0,211607669.0,92.0,...,190.0,74333.0,536.0,136.0,36321847.0,172.0,5022621.0,5639.0,7208651.0,5285340.0
3,Flowers,Miley Cyrus,1/12/2023,Flowers - Single,4,444.9,2.031281e+09,269802.0,136569078.0,85.0,...,394.0,1474799.0,2182.0,264.0,24684248.0,210.0,190260277.0,203384.0,NaN,11822942.0
4,Houdini,Eminem,5/31/2024,Houdini,5,423.3,1.070349e+08,7223.0,151469874.0,88.0,...,182.0,12185.0,1.0,82.0,17660624.0,105.0,4493884.0,7006.0,207179.0,457017.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,For the Last Time,$uicideboy$,9/5/2017,For the Last Time,4585,19.4,3.050500e+08,65770.0,5103054.0,71.0,...,3.0,6.0,NaN,2.0,14217.0,NaN,20104066.0,13184.0,50633006.0,656337.0
4596,Dil Meri Na Sune,Atif Aslam,7/27/2018,"Dil Meri Na Sune (From ""Genius"")",4575,19.4,5.228236e+07,4602.0,1449767.0,56.0,...,1.0,412.0,NaN,1.0,927.0,NaN,NaN,NaN,NaN,193590.0
4597,Grace (feat. 42 Dugg),Lil Baby,2/28/2020,My Turn,4571,19.4,1.899727e+08,72066.0,6704802.0,65.0,...,19.0,204.0,NaN,1.0,74.0,6.0,84426740.0,28999.0,NaN,1135998.0
4598,Nashe Si Chadh Gayi,Arijit Singh,11/8/2016,November Top 10 Songs,4591,19.4,1.454670e+08,14037.0,7387064.0,66.0,...,1.0,1200.0,NaN,NaN,NaN,7.0,6817840.0,NaN,NaN,448292.0
4599,Me Acostumbre (feat. Bad Bunny),Arc��,4/11/2017,Me Acostumbre (feat. Bad Bunny),4593,19.4,2.557407e+08,32138.0,14066526.0,64.0,...,11.0,2083.0,NaN,4.0,127479.0,4.0,69006739.0,11320.0,NaN,767006.0

#### Handle duplicated tracks

For the 2024 dataset, we don't have information about tracks' features, so I will only care about the tracks' names and artists. I will handle the duplicated as follow:

- For ranking or score column, only keep the highest rank or score
- For count columns, use the sum

In [18]:
# Handle duplicated tracks in All Time Rank, Track Score, and popularity columns, and other count columns

data_2024["All Time Rank"] = data_2024.groupby(['Track', 'Artist'])["All Time Rank"].transform('min')
data_2024["Track Score 2024"] = data_2024.groupby(['Track', 'Artist'])["Track Score 2024"].transform('max')
data_2024["Spotify Popularity 2024"] = data_2024.groupby(['Track', 'Artist'])["All Time Rank"].transform('max')

remove_cols = ["Track", "Artist", "Release Date", "Album Name", "All Time Rank", "Track Score 2024", "Spotify Popularity 2024"]
count_2024_cols = [col for col in data_2024.columns.to_list() if col not in remove_cols]
data_2024[count_2024_cols] = data_2024.groupby(['Track', 'Artist'])[count_2024_cols].transform('sum')

In [19]:
data_2024.drop_duplicates(subset=["Track", "Artist"], keep="first", inplace=True)

For the 2023 dataset

In [20]:
duplicated_song_2023 = data_2023[data_2023[["Track", "Artist"]].duplicated()]["Track"].values
data_2023[data_2023["Track"].isin(duplicated_song_2023)]

,Track,Artist,Release Date,Spotify Playlist Count 2023,Spotify Chart Counts 2023,Streams 2023,Apple Music Playlist Count 2023,Apple Music Chart Counts 2023,Deezer Playlist Count 2023,Deezer Chart Counts 2023,...,Bpm,Key,Mode,Danceability %,Valence %,Energy %,Acousticness %,Instrumentalness %,Liveness %,Speechiness %
178,SNAP,Rosa Linn,3/19/2022,3202,18,726307468.0,148,80,226,24,...,170,NaN,Major,56,53,64,11,0,45,6
345,SPIT IN MY FACE!,ThxSoMch,10/31/2022,629,14,303216294.0,32,3,9,0,...,94,G#,Major,73,65,79,5,2,11,6
372,About Damn Time,Lizzo,7/15/2022,2332,2,723894473.0,0,0,25,0,...,109,A#,Minor,84,72,74,10,0,34,7
482,SPIT IN MY FACE!,ThxSoMch,10/31/2022,573,0,301869854.0,1,0,18,0,...,166,C#,Major,70,57,57,9,20,11,7
512,Take My Breath,The Weeknd,8/6/2021,2597,0,130655803.0,17,80,38,0,...,121,A#,Minor,70,35,77,1,0,26,4
616,Take My Breath,The Weeknd,8/6/2021,6392,0,432702334.0,174,73,344,0,...,121,G#,Major,75,53,74,2,0,11,5
764,About Damn Time,Lizzo,4/14/2022,9021,0,723894473.0,242,49,272,21,...,109,A#,Minor,84,72,74,10,0,34,7
873,SNAP,Rosa Linn,3/19/2022,1818,0,711366595.0,3,0,63,0,...,170,NaN,Major,56,52,64,11,0,45,7

For Key, by manually searching, I got that:

SPIT IN MY FACE! : Key C#, BPM: 166

SNAP: Key C#, BPM : 170 (correct)

About Damn Time: Key A#, BPM: 109

Take My Breath: Key G#, BPM: 121, Major


So I will keep rows that having these features. For About Damn Time, just use their average for features

In [21]:
index_to_remove = [345, 178, 512]
data_2023.drop(index=index_to_remove, inplace=True)

In [22]:
list_of_numerical_features = ['Bpm',
 'Danceability %',
 'Valence %',
 'Energy %',
 'Acousticness %',
 'Instrumentalness %',
 'Liveness %',
 'Speechiness %']

data_2023[list_of_numerical_features] = data_2023.groupby(["Track", "Artist"])[list_of_numerical_features].transform('mean')
data_2023.drop_duplicates(subset=["Track", "Artist"], keep="first", inplace=True)

#### Handle missing datas

The 2023 dataset has 3 columns which have missing values: Key, Shazam Chart Count and Streams 

The column Streams only have 1 missing data, so we can drop it

Replace missing values in Shazam Chart Count by mean of Apple Music Chart Count and Spotify Chart Count

For Key, there are various missing values. We cannot mannually search and replace all of them, and cannot replace by value in any other rows. So just leave them as missing values since about 25 missing values in key will not affect the overall distribution of key among 900 tracks

However, we still have missing data in Track and Artist column, but they are not "NaN". Instead, they are blank column. We need to handle them as well

In [23]:
# handle missing data
data_2023[data_2023["Streams 2023"].isnull()]
data_2023 = data_2023.drop(574)
data_2023["Shazam Chart Counts 2023"]=data_2023["Shazam Chart Counts 2023"].fillna((data_2023["Apple Music Chart Counts 2023"] + data_2023["Spotify Chart Counts 2023"]) / 2)

In [24]:
data_2023.columns[data_2023.isnull().any()].tolist() # check after handling missing data (NaN)

['Key']

In [25]:
data_2023[data_2023['Track'].str.strip() == ""] # check missing data in Track column

,Track,Artist,Release Date,Spotify Playlist Count 2023,Spotify Chart Counts 2023,Streams 2023,Apple Music Playlist Count 2023,Apple Music Chart Counts 2023,Deezer Playlist Count 2023,Deezer Chart Counts 2023,...,Bpm,Key,Mode,Danceability %,Valence %,Energy %,Acousticness %,Instrumentalness %,Liveness %,Speechiness %
174,,YOASOBI,4/12/2023,356,16,143573775.0,35,102,8,1,...,166.0,C#,Major,57.0,84.0,94.0,11.0,0.0,37.0,9.0
374,,Fujii Kaze,5/20/2020,685,14,403097450.0,24,94,9,0,...,158.0,F#,Minor,60.0,52.0,76.0,17.0,0.0,19.0,5.0

In [26]:
data_2023.drop([174, 374], inplace=True) # drop them

In [27]:
data_2023[data_2023["Artist"].str.strip() == ""] # Check missing data in Artist column

Empty DataFrame
Columns: [Track, Artist, Release Date, Spotify Playlist Count 2023, Spotify Chart Counts 2023, Streams 2023, Apple Music Playlist Count 2023, Apple Music Chart Counts 2023, Deezer Playlist Count 2023, Deezer Chart Counts 2023, Shazam Chart Counts 2023, Bpm, Key, Mode, Danceability %, Valence %, Energy %, Acousticness %, Instrumentalness %, Liveness %, Speechiness %]
Index: []

[0 rows x 21 columns]

For 2024 dataset, there are only 5 rows having missing values, so we can safely delete them

In [28]:
data_2024[data_2024.isnull().any(axis=1)] # drop them

,Track,Album Name,Artist,Release Date,All Time Rank,Track Score 2024,Spotify Streams 2024,Spotify Playlist Count 2024,Spotify Playlist Reach 2024,Spotify Popularity 2024,...,Apple Music Playlist Count 2024,AirPlay Spins 2024,SiriusXM Spins 2024,Deezer Playlist Count 2024,Deezer Playlist Reach 2024,Amazon Playlist Count 2024,Pandora Streams 2024,Pandora Track Stations 2024,Soundcloud Streams 2024,Shazam Counts 2024
311,Cool,JnD Mix,NaN,5/25/2024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
480,I Wanna Party,I Wanna Party - Single,NaN,5/31/2024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1345,Marlboro Remix,Marlboro Remix - Single,NaN,6/7/2024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1561,Melting,Melting - Single,NaN,6/10/2024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3402,La ��ltima Vez (Yo Te Per,La ��ltima Vez (Yo Te Perd��),NaN,5/2/2024,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
data_2024.dropna(inplace=True) # drop na values in 2024 dataset

In [30]:
data_2024[data_2024.isnull().any(axis=1)] # check

Empty DataFrame
Columns: [Track, Album Name, Artist, Release Date, All Time Rank, Track Score 2024, Spotify Streams 2024, Spotify Playlist Count 2024, Spotify Playlist Reach 2024, Spotify Popularity 2024, YouTube Views 2024, YouTube Likes 2024, TikTok Posts 2024, TikTok Likes 2024, TikTok Views 2024, YouTube Playlist Reach 2024, Apple Music Playlist Count 2024, AirPlay Spins 2024, SiriusXM Spins 2024, Deezer Playlist Count 2024, Deezer Playlist Reach 2024, Amazon Playlist Count 2024, Pandora Streams 2024, Pandora Track Stations 2024, Soundcloud Streams 2024, Shazam Counts 2024]
Index: []

[0 rows x 26 columns]

In [31]:
data_2024[data_2024['Track'].str.strip() == ""] # check missing data in Track column

,Track,Album Name,Artist,Release Date,All Time Rank,Track Score 2024,Spotify Streams 2024,Spotify Playlist Count 2024,Spotify Playlist Reach 2024,Spotify Popularity 2024,...,Apple Music Playlist Count 2024,AirPlay Spins 2024,SiriusXM Spins 2024,Deezer Playlist Count 2024,Deezer Playlist Reach 2024,Amazon Playlist Count 2024,Pandora Streams 2024,Pandora Track Stations 2024,Soundcloud Streams 2024,Shazam Counts 2024
146,,,FLI:P,4/7/2023,147.0,125.4,8.028757e+06,1972.0,488653.0,147.0,...,1.0,373.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,220198.0
161,,3,(),1/5/2022,162.0,119.5,5.484080e+05,130.0,20518.0,162.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,69763.0
351,,,YOASOBI,4/12/2023,351.0,81.8,1.481006e+09,206671.0,32689574.0,351.0,...,177.0,6219.0,0.0,21.0,105975.0,34.0,3679638.0,2395.0,0.0,3443506.0
460,,,ALEX&RUS,7/3/2019,460.0,71.9,5.283020e+07,14893.0,1344212.0,460.0,...,2.0,430.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3415809.0
804,,Show - Single,Ado,9/6/2023,800.0,54.2,3.034395e+08,52668.0,7471859.0,800.0,...,64.0,1435.0,0.0,3.0,4313.0,10.0,0.0,0.0,0.0,538733.0
1020,,,HoneyWorks,11/21/2022,1014.0,47.7,2.319193e+07,5912.0,438018.0,1014.0,...,3.0,80.0,0.0,0.0,0.0,6.0,46380.0,60.0,0.0,188814.0
1079,,- Single,,3/22/2024,1073.0,46.2,5.599896e+06,404.0,264984.0,1073.0,...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,31984.0
1292,,- Single,Jazzdauren,3/1/2024,1287.0,41.5,2.902263e+06,968.0,474517.0,1287.0,...,11.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,904938.0
1489,,Bibbidiba - Single,Hoshimachi Suisei,3/23/2024,1482.0,38.1,2.125507e+07,1754.0,3985309.0,1482.0,...,2.0,38.0,0.0,1.0,7336.0,7.0,0.0,0.0,0.0,41209.0
1520,,- Single,Ptrp Studio,6/2/2022,1515.0,37.8,1.321983e+07,3136.0,395560.0,1515.0,...,0.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1681,,,Tatsuya Kitani,7/7/2023,1669.0,35.7,1.730188e+08,22899.0,7048784.0,1669.0,...,27.0,525.0,0.0,5.0,35588.0,11.0,58750.0,185.0,0.0,394480.0
1733,,,Md Faisal Ahmed,7/9/2023,1731.0,35.1,2.274000e+03,0.0,0.0,1731.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1821,,,Parkmalody,10/14/2023,1804.0,34.2,1.390033e+07,1737.0,402173.0,1804.0,...,3.0,958.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24734.0
1936,,,ANNA ASTI,7/14/2023,1922.0,33.0,1.708036e+07,5909.0,554886.0,1922.0,...,17.0,1220.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1065042.0
2293,,- Single,,12/8/2022,2279.0,30.0,4.681620e+05,114.0,21665.0,2279.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,95147.0
2383,,- Single,,5/2/2024,2374.0,29.3,0.000000e+00,0.0,0.0,2374.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2431,,The End,Lusia Chebotina,10/29/2021,2421.0,29.0,3.231889e+07,13584.0,1196310.0,2421.0,...,23.0,902.0,0.0,3.0,657583.0,0.0,0.0,0.0,0.0,1544949.0
2663,,,Bonnadol,3/15/2023,2652.0,27.4,4.787560e+05,207.0,18460.0,2652.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4666.0
2788,,,Djpaoremix,2/3/2023,2792.0,26.6,1.342740e+05,70.0,4970.0,2792.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3926.0
2820,,,SPRITE,4/29/2021,2803.0,26.5,9.126545e+06,2349.0,139340.0,2803.0,...,7.0,819.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117936.0
2840,,- Single,Akris & Teddy,5/31/2024,2828.0,26.3,3.060400e+05,1.0,13.0,2828.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,610446.0
2933,,,ANNA ASTI,6/3/2022,2922.0,25.8,2.108131e+07,7633.0,496465.0,2922.0,...,20.0,1266.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1180992.0
3054,,,tuki.,9/29/2023,3050.0,25.1,6.934015e+07,4747.0,3839570.0,3050.0,...,26.0,152.0,0.0,1.0,9615.0,2.0,0.0,0.0,0.0,206249.0
3096,,- Single,Wallem,3/12/2024,3081.0,24.9,3.636983e+06,776.0,267020.0,3081.0,...,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,600644.0
3329,,,MORGENSHTERN,3/8/2024,3328.0,23.8,1.117043e+07,2065.0,364180.0,3328.0,...,11.0,3.0,0.0,2.0,34118.0,0.0,0.0,0.0,0.0,428081.0
3333,,- Single,NLO,5/2/2023,3338.0,23.8,7.900402e+06,4782.0,367497.0,3338.0,...,7.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,998296.0
3389,,,fellow fellow,8/29/2023,3378.0,23.6,4.375681e+07,6019.0,1678608.0,3378.0,...,10.0,1347.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,90968.0
3471,,- Single,TaitosmitH,3/26/2024,3462.0,23.2,2.759335e+06,248.0,177260.0,3462.0,...,4.0,55.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17660.0
3486,,,Moreart,12/4/2020,3475.0,23.2,6.035858e+07,32582.0,1788403.0,3475.0,...,4.0,340.0,0.0,0.0,0.0,3.0,2287886.0,1511.0,0.0,3413948.0
3512,,,YOUNGOHM,1/25/2023,3498.0,23.1,1.774559e+07,2837.0,283039.0,3498.0,...,6.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,62461.0
3597,,,Mrs. GREEN APPLE,4/11/2024,3573.0,22.7,2.622260e+07,921.0,7492428.0,3573.0,...,30.0,255.0,0.0,0.0,0.0,3.0,26690.0,0.0,0.0,59611.0
3602,,- Single,A.V.G,7/17/2023,3593.0,22.7,1.069492e+07,5363.0,288263.0,3593.0,...,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1593368.0
3858,,,,1/5/2024,3834.0,21.8,5.511465e+07,5585.0,6081785.0,3834.0,...,25.0,334.0,0.0,1.0,20798.0,4.0,0.0,0.0,0.0,200168.0
4001,,,Aimer,12/6/2021,3975.0,21.4,2.276969e+08,34276.0,6961653.0,3975.0,...,35.0,1922.0,0.0,5.0,8662.0,3.0,662602.0,324.0,0.0,403076.0
4129,,,Omoinotake,1/24/2024,4114.0,21.0,4.608209e+07,1755.0,5204396.0,4114.0,...,36.0,442.0,0.0,1.0,9615.0,3.0,0.0,0.0,0.0,290079.0
4170,,,,1/20/2021,4151.0,20.8,2.197052e+07,11053.0,436364.0,4151.0,...,17.0,11.0,0.0,2.0,5452.0,0.0,0.0,0.0,0.0,2938941.0
4187,,,Galibri & Mavik,5/19/2021,4149.0,20.8,2.514967e+07,13174.0,603919.0,4149.0,...,17.0,282.0,0.0,1.0,56252.0,0.0,0.0,0.0,0.0,2098943.0
4354,,,Jah Khalib,12/2/2022,4322.0,20.2,1.456634e+07,6708.0,323589.0,4322.0,...,7.0,1067.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,989901.0
4402,,- EP,WINE,12/19/2022,4393.0,20.0,2.761930e+05,226.0,76928.0,4393.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,173.0
4438,,,Eslam Kabonga,6/16/2023,4407.0,19.9,1.360824e+07,23.0,178.0,4407.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15667505.0,0.0
4464,,Kizuna No Kiseki,MAN WITH A MISSION,4/10/2023,4429.0,19.8,9.847602e+07,15170.0,5083474.0,4429.0,...,36.0,669.0,0.0,6.0,36038.0,11.0,0.0,0.0,0.0,404281.0
4526,,,Lamis Kan,7/27/2021,4525.0,19.6,4.107109e+07,14309.0,1842678.0,4525.0,...,3.0,789.0,0.0,1.0,74982.0,0.0,0.0,0.0,0.0,1266792.0

In [32]:
data_2024.drop(data_2024[data_2024["Track"].str.strip() == ""].index, inplace=True) # drop them

In [33]:
data_2024[data_2024["Artist"].str.strip() == ""] # check missing data in Artist column

,Track,Album Name,Artist,Release Date,All Time Rank,Track Score 2024,Spotify Streams 2024,Spotify Playlist Count 2024,Spotify Playlist Reach 2024,Spotify Popularity 2024,...,Apple Music Playlist Count 2024,AirPlay Spins 2024,SiriusXM Spins 2024,Deezer Playlist Count 2024,Deezer Playlist Reach 2024,Amazon Playlist Count 2024,Pandora Streams 2024,Pandora Track Stations 2024,Soundcloud Streams 2024,Shazam Counts 2024
344,kompa pasi�,kompa pasi�,,4/12/2024,345.0,82.5,29458027.0,2602.0,6588032.0,345.0,...,9.0,132.0,0.0,6.0,73462.0,0.0,0.0,0.0,365682.0,2085595.0
3289,Baby you,Baby you,,1/18/2023,3273.0,24.0,30361093.0,6140.0,1321340.0,3273.0,...,16.0,114.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,250538.0
4192,sup�,sup�,,8/11/2023,4188.0,20.7,63642484.0,15618.0,1035077.0,4188.0,...,1.0,0.0,0.0,0.0,0.0,0.0,89501.0,93.0,0.0,400490.0

In [34]:
data_2024.drop(data_2024[data_2024["Artist"].str.strip() == ""].index, inplace=True) # drop them

In [35]:
data_2023.to_csv("../data/data_2023_clean.csv")
data_2024.to_csv("../data/data_2024_clean.csv")